---
kind: pipeline
type: docker
name: run development version

steps:
  - name: run dev
    image: docker/compose:1.25.5
    environment:
      MOODLE_PASSWORD:
        from_secret: MOODLE_PASSWORD
      MOODLE_USERNAME:
        from_secret: MOODLE_USERNAME
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker-compose -f /drone/src/docker-compose.dev.yml up --detach --build
  - name: slack
    image: plugins/slack
    settings:
      channel: drone-ci
      template: >
        {{build.event}} on {{build.branch}}
        {{#success build.status}}
        build {{build.number}} succeeded!
        {{else}}
        build {{build.number}} failed!
        {{/success}}
      webhook:
        from_secret: SLACK_WEBHOOK_URL
    when:
      status: [ success, failure ]

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch: develop
  event: push
