---
kind: pipeline
type: docker
name: notification

trigger:
  event: [push, pull_request]

steps:
  - name: slack before
    image: plugins/slack
    failure: ignore
    settings:
      channel: drone-ci
      template: >
        {{ uppercasefirst build.event }} on branch {{ build.branch }} from repo {{repo.name}}

        Request to deploy build #{{build.number}}

        <{{ build.link }}|Visit build page ➡️>
      webhook:
        from_secret: SLACK_WEBHOOK_URL

---
kind: pipeline
type: docker
name: security

trigger:
  event: [push, pull_request]
  branch:
    exclude:
      - master

steps:
  - name: bandit test
    failure: ignore
    image: python:3.8-buster
    commands:
      - pip install bandit
      - bandit -r ./ -ll
  - name: safety check
    failure: ignore
    image: python:3.8-buster
    commands:
      - pip install safety
      - safety check
      - safety check -r requirements.txt

---
kind: pipeline
type: docker
name: deploy

trigger:
  event:
    - promote
  target:
    - production

steps:
  - name: deploy prod
    image: docker/compose:1.25.5
    environment:
      MOODLE_PASSWORD:
        from_secret: MOODLE_PASSWORD
      MOODLE_USERNAME:
        from_secret: MOODLE_USERNAME
      MOODLE_DIRECTORY:
        from_secret: MOODLE_DIRECTORY
      HC_UUID:
        from_secret: HC_UUID
      SLACK_NOTIFIER_HOOK:
        from_secret: SLACK_NOTIFIER_HOOK
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - /bin/sh /drone/src/docker/scripts/deploy.sh
  - name: slack notification
    image: plugins/slack
    failure: ignore
    settings:
      channel: drone-ci
      webhook:
        from_secret: SLACK_WEBHOOK_URL
      template: >
        {{#if build.pull }}
          *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}*: <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
        {{else}}
          *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}* (type: `{{ build.event }}`)
        {{/if}}

        Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>

        Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>

        Author: {{ build.author }}

        <{{ build.link }}|Visit build page ➡️>

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
