version: "3.7"

services:
  moodle-scraper:
    container_name: moodle-scraper
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MOODLE_USERNAME
      - MOODLE_PASSWORD
      - UID=1000
      - GID=1000
      - TZ
