version: "3.8"

services:
  scraper:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HC_UUID
      - MOODLE_PASSWORD
      - MOODLE_USERNAME
      - SLACK_NOTIFIER_HOOK
