version: "3.8"

services:
  scraper:
    container_name: moodle-scraper
    image: ghcr.io/gordonpn/moodle-scraper:stable
    user: 1001:1001
    restart: unless-stopped
    command: [ "python", "./main.py", "--automated" ]
    volumes:
      - /mnt/glusterfs/syncthing/moodle:/home/appuser/courses
    environment:
      - GID=1001
      - UID=1001
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 60s
        max_attempts: 5
        window: 120s
      placement:
        constraints:
          - node.labels.persistence == true
