version: "3.7"

services:
  moodle-scraper:
    container_name: moodle-scraper-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - GID=1000
      - MOODLE_PASSWORD
      - MOODLE_USERNAME
      - TZ
      - UID=1000
