version: "3.8"

services:
  moodle-scraper:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GID=1000
      - HC_UUID
      - MOODLE_PASSWORD
      - MOODLE_USERNAME
      - TZ=America/Montreal
      - UID=1000
