version: "3.7"

services:
  moodle-scraper:
    container_name: moodle-scraper
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ${MOODLE_DIRECTORY}:/home/appuser/courses
    environment:
      - GID=1000
      - MOODLE_PASSWORD
      - MOODLE_USERNAME
      - TZ=America/Montreal
      - UID=1000
