version: "3.7"

services:
  moodle-scraper-dev:
    container_name: moodle-scraper-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - GID=1000
      - MOODLE_PASSWORD
      - MOODLE_USERNAME
      - TZ=America/Montreal
      - UID=1000
      - DEV_RUN
