name: publish docker
on:
  push:
  pull_request:

jobs:
  docker:
    strategy:
      matrix:
        branches: [ develop, master ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branches }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build Docker images and publish
        env:
          BRANCH: ${{ matrix.branches }}
        run: |
          DOCKER_TAG="latest"
          [ "$BRANCH" = "master" ] && DOCKER_TAG="stable"
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker buildx build -t ghcr.io/gordonpn/moodle-scraper:"$DOCKER_TAG" --platform linux/amd64,linux/arm64 --push .

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always()
